### PR TITLE
Use UUIDSerializer as contextual in Avro.default

### PR DESCRIPTION
**Pull request by vladimirfx**
Current code in SerializersModule is no op:

```kotlin
 mapOf(
            UUID::class to UUIDSerializer()
         )
```

### CODE REVIEW

**Comment by vladimirfx** [comment]
This PR is depends on #88

**Comment by thake** [comment]
@vladimirfx thanks for fixing :+1: 
I will merge this as soon as #98 is merged

**Comment by thake** [comment]
@vladimirfx can you rebase on the current master so that the CI build works?

**Comment by vladimirfx** [comment]
> @vladimirfx can you rebase on the current master so that the CI build works?

done

**Review by thake — APPROVED** [review]

**Pull request merged**
