### PR TITLE
Value (former inline) class serialization support

### PR DESCRIPTION
**Pull request by vladimirfx**
Depends on Serialization 1.2 (Kotlin 1.5)

### CODE REVIEW

**Comment by thake** [comment]
@vladimirfx Thanks again for your contribution!

**Comment by vladimirfx** [comment]
@thake Can I ask you to release avro4k?

**Comment by thake** [comment]
@vladimirfx I'll release it tomorrow. Sorry for letting you wait.

**Comment by thake** [comment]
@vladimirfx Version 1.3.0 has been released to maven central.

**Pull request merged**
